require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Rails/Output:
  Exclude:
    - "app/views/**/*.rb"
