require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Lint/MissingSuper:
  Exclude:
    - "app/components/**/*.rb"
